// <auto-generated />
using System;
using ConradEnergy.EFCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConradEnergy.EFCore.Migrations
{
    [DbContext(typeof(ConradEnergyContext))]
    [Migration("20220817100606_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ConradEnergyCore.Data.Entities.ElectricityDemand", b =>
                {
                    b.Property<DateTime>("SettlementDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SettlementPeriod")
                        .HasColumnType("int");

                    b.HasKey("SettlementDate", "SettlementPeriod");

                    b.ToTable("ElectricityDemands");
                });
#pragma warning restore 612, 618
        }
    }
}
